### ISSUE TITLE
abstractruleの拡張

### ISSUE THREAD

**Issue by H1025** [m-seikou/hashValidator#9]
独自のruleを使用可能にする

**Comment by m-seikou** [comment]
独自のルールによるチェックは`ruleInterface`を実装したクラスを作成し、`type: クラス名`で実現可能
`ruleInterface::dump()`の拡張が必要となった場合は`abstractRule`を修正する必要が出てくる。

**Comment by m-seikou** [comment]
例えば
```php
public function dump();
```
を
```php
public function dump(closure $before = null, closure $after = null);
```
みたいな形で再帰的に注入できるよな形か?

**Comment by m-seikou** [comment]
hashVaridatorにも`closure $after = null`を足さないとか。
beforeはいらない気がする

**Comment by m-seikou** [comment]
@H1025 
これでどうです
```php
// $dump にAbstractRuleのdump配列が渡される
hashVaridator->dump(function($dump){ return $dump });
```

**Comment by H1025** [comment]
ありがとうございます！こちらで問題ありません。
